version: '3'
services:
  dummer:
    build:
      context: ./dummer
    image: dummer:1
    environment:
      - RATE
    depends_on:
      - target
  target:
    build: out_forward
    image: out_forward:1
    depends_on:
      - receiver
  receiver:
    build: receiver
    image: receiver:1
    volumes:
      - ./data/out_forward:/var/log/flunetd_stats
